server:
  port: 8967
spring:
  thymeleaf:
    prefix: classpath:/templates/
  application:
    name: bot-service
  main:
    allow-bean-definition-overriding: true
logging:
  file:
    name: logs/bot.log